{% set name = "textual-fastdatatable" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/textual_fastdatatable-{{ version }}.tar.gz
  sha256: 56b035e22d694fa902a8b80120765addd6e32f4eee0151ee46fa6ab1deaad59e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - pytz >=2023,<2025
    - tzdata >=2023
    - python >={{ python_min }},<4.0.0
    - textual >=0.89.1
    - pyarrow >=16.1.0

test:
  imports:
    - textual_fastdatatable
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tconbeer/textual-fastdatatable
  summary: A performance-focused reimplementation of Textual's DataTable widget, with a pluggable data storage backend.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
