{% set name = "textual-fastdatatable" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/textual_fastdatatable-{{ version }}.tar.gz
  sha256: cb99e208fb96c7eb5cfb7f225a280da950bd8cfb29d685a49071787c80218901

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - numpy >=2.1.0,<2.3.0
    - pandas >=2.2.1,<3
    - pytz >=2023,<2025
    - tzdata >=2023
    - python >={{ python_min }},<4.0.0
    - textual >=0.89.1
    - pyarrow >=18.1.0,<22

test:
  imports:
    - textual_fastdatatable
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tconbeer/textual-fastdatatable
  summary: A performance-focused reimplementation of Textual's DataTable widget, with a pluggable data storage backend.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
