{% set name = "textual-fastdatatable" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/textual_fastdatatable-{{ version }}.tar.gz
  sha256: e39b8ba54cc16fec47f9af8320589707862369bc85138c26bf54f0dc9b69368c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - pytz >=2023,<2025
    - tzdata >=2023
    - python >=3.8.0,<4.0.0
    - textual >=0.41.0
    - pyarrow >=7.0.0

test:
  imports:
    - textual_fastdatatable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tconbeer/textual-fastdatatable
  summary: A performance-focused reimplementation of Textual's DataTable widget, with a pluggable data storage backend.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
