{% set name = "textual-fastdatatable" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/textual_fastdatatable-{{ version }}.tar.gz
  sha256: d66581d0d9f6b5dccf364a405e6e5cb733e1cacddc612b4f61dee06d1aac7b5e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - textual >=0.38.0
    - pyarrow >=7.0.0

test:
  imports:
    - textual_fastdatatable
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tconbeer/textual-fastdatatable
  summary: A performance-focused reimplementation of Textual's DataTable widget, with a pluggable data storage backend.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
