schema_version: 1

context:
  name: textual-fastdatatable
  version: 0.16.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/textual_fastdatatable-${{ version }}.tar.gz
  sha256: 9d91f6d257bde25e244379d03b3fbcc92edafcfae983d8270ad34b0f344f1d97

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0.0
    - textual >=7.3.0
    - pyarrow >=18.1.0
    - typing_extensions >=4.4.0
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - textual_fastdatatable

about:
  summary: A performance-focused reimplementation of Textual's DataTable widget, with a pluggable data storage backend.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tconbeer/textual-fastdatatable

extra:
  recipe-maintainers:
    - xhochy
