schema_version: 1

context:
  name: textual-fastdatatable
  version: 0.15.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/textual_fastdatatable-${{ version }}.tar.gz
  sha256: b4c5ab6c90d510c52bfbbc19d4a978a6f0311b358a9bc7bbaefe2870dd730676

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - numpy >=2.1.0,<2.3.0
    - pandas >=2.2.1,<3
    - python >=${{ python_min }},<4.0.0
    - textual >=0.89.1
    - pyarrow >=18.1.0,<22
tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - textual_fastdatatable

about:
  summary: A performance-focused reimplementation of Textual's DataTable widget, with a pluggable data storage backend.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tconbeer/textual-fastdatatable

extra:
  recipe-maintainers:
    - xhochy
